Clear-Host

if(!($Env:PSModulePath.Split(";") | where {$PSItem -like "*\Modules\APS*"})){
    $Env:PSModulePath = $Env:PSModulePath + ";$PSScriptRoot\Modules"
}

New-Variable -Name APSBase -Value "$PSScriptRoot"
Export-ModuleMember -Variable APSBase

Write-Host "Windows PowerShell"
Write-Host "Hi! It is $(Get-Date -Format g)"
Write-Host "You are working as $env:UserName"
Write-Host $(Get-Weather)
Write-Host ""

# SIG # Begin signature block
# MIIFeQYJKoZIhvcNAQcCoIIFajCCBWYCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUq7kJZriF5DIRQgL3RSf8Dr8C
# agagggMQMIIDDDCCAfSgAwIBAgIQfziWHbCKBoRNGa23h81cKTANBgkqhkiG9w0B
# AQsFADAeMRwwGgYDVQQDDBNQb3dlclNoZWxsIGFrb3R1IENBMB4XDTIyMDIwMTEz
# MDExMloXDTI3MDIwMTEzMTExM1owHjEcMBoGA1UEAwwTUG93ZXJTaGVsbCBha290
# dSBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJ5Jah2xqCyY33yT
# xhz7JjIQofP86RYwn5arpiQfKz87xvKTzOcVm9Pf3jrpKkcUnGL7PKqGDAX6HL5r
# GQ7/2RPlnH7cSYIM9vYYmR7vgUUgQACsYVOO5UcrlDT9ga387gd7YInmSn/icot3
# b2gvCf1Ok3OT05d8Vu4PzzYXNRvc6pIgnQ++ENakvB6LLSoso3OuZZoFhHpufD0/
# 8ac21gw9ZeweFtQzy8BAkMbPCSSymiYduLPF4XEb1vo2w3fHDl/LYCfrJWOHTELS
# IjpRLJQYbJnewBZ1x6jXRB0dTbUrO3C5UPoKXYPMIMi5Slvk1XPDHeXLOXAb4ZTO
# EHV325kCAwEAAaNGMEQwDgYDVR0PAQH/BAQDAgeAMBMGA1UdJQQMMAoGCCsGAQUF
# BwMDMB0GA1UdDgQWBBR1hk5NfI7NaI/MFxkS4z6wB5uaszANBgkqhkiG9w0BAQsF
# AAOCAQEABoUXCtmgDOiK6QjrzONCSE+7NbYrwzPonxGY0PNvmxf5Y6CcCK0Nga8v
# ImAZM9cXAGOUZE0wZQUODHW4OxbW1kgzS4OvOQZZUeSPNG7OLxttYkF5+5Pfs8RY
# AxkI0XYP3JId4Fx5E8ByMGx7wOpyVcLOCU+DEpEf21tHa4xQ5RGeKTcE7hRROLpg
# g50DeoiSAeAmAH2K2l2uCPb+fP+MeEFH9THGPYJbWozU9Zq90Az3HCEn2dkPXKof
# ZfBOJt3/WwSWGtYZqf0cAooTcKlO1TrreAmh4uuslfM7F579xKqX8ou1JzRQ2n/M
# WRajsdVGAXYebpyYbjiGjNKoGzWS8DGCAdMwggHPAgEBMDIwHjEcMBoGA1UEAwwT
# UG93ZXJTaGVsbCBha290dSBDQQIQfziWHbCKBoRNGa23h81cKTAJBgUrDgMCGgUA
# oHgwGAYKKwYBBAGCNwIBDDEKMAigAoAAoQKAADAZBgkqhkiG9w0BCQMxDAYKKwYB
# BAGCNwIBBDAcBgorBgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAjBgkqhkiG9w0B
# CQQxFgQUtVh4J9wo+Yi/WDs6GVL6nxyWiGUwDQYJKoZIhvcNAQEBBQAEggEAi5y5
# kyn6QFEMLqmhVe2sO+OGp7MZHCUxoUGBm/bawZvdoU8WFr1Pqe/rHAsoVvLfwnZG
# Up8N5gGkRysU7MBZ6kcK7lhKvdu1ewkNpjHiwD5/RAcXzRxxmUvBiQAE/iZv9+tn
# Zr12fnKihdhQdVLESmWRvuYA49vMaH0i2G/DAvox+EbiwGy2yP/bFm1qvARhNo7P
# gvxnyXZhe3mEOotulf3SStDmY+DOG6kvbsqEea1n95d6RurSa3/aJVVWseN7Eazg
# iNpW19dNNe8bLaAPG9WuqQb6lIiv0GXQIPZFHYivjOyGzgTNzw28GnijbsHK1xGt
# p6dkMOtcCHU8gPne7g==
# SIG # End signature block
